undoes the change of config/application.rb part.3
元に戻し、“NoMethodError: undefined method `[]' for nil:NilClass”の解決策を別の方法で試す。